require_relative 'baseItem'

class RPG::State < RPG::BaseItem
	def initialize
		super
		@restriction = 0
		@priority = 50
		@remove_at_battle_end = false
		@remove_by_restriction = false
		@auto_removal_timing = 0
		@min_turns = 1
		@max_turns = 1
		@remove_by_damage = false
		@chance_by_damage = 100
		@remove_by_walking = false
		@steps_to_remove = 100
		@message1 = ''
		@message2 = ''
		@message3 = ''
		@message4 = ''
	end

	def initialize(json)
		super(json)
		@restriction = json["restriction"]
		@priority = json["priority"]
		@remove_at_battle_end = json["removeAtBattleEnd"]
		@remove_by_restriction = json["removeByRestriction"]
		@auto_removal_timing = json["autoRemovalTiming"]
		@min_turns = json["minTurns"]
		@max_turns = json["maxTurns"]
		@remove_by_damage = json["removeByDamage"]
		@chance_by_damage = json["chanceByDamage"]
		@remove_by_walking = json["removeByWalking"]
		@steps_to_remove = json["stepsToRemove"]
		@message1 = json["message1"]
		@message2 = json["message2"]
		@message3 = json["message3"]
		@message4 = json["message4"]
	end

	def updateFromJson(json)
		super(json)
		@restriction = json["restriction"] if json["restriction"]
		@priority = json["priority"] if json["priority"]
		@remove_at_battle_end = json["removeAtBattleEnd"] if json["removeAtBattleEnd"]
		@remove_by_restriction = json["removeByRestriction"] if json["removeByRestriction"]
		@auto_removal_timing = json["autoRemovalTiming"] if json["autoRemovalTiming"]
		@min_turns = json["minTurns"] if json["minTurns"]
		@max_turns = json["maxTurns"] if json["maxTurns"]
		@remove_by_damage = json["removeByDamage"] if json["removeByDamage"]
		@chance_by_damage = json["chanceByDamage"] if json["chanceByDamage"]
		@remove_by_walking = json["removeByWalking"] if json["removeByWalking"]
		@steps_to_remove = json["stepsToRemove"] if json["stepsToRemove"]
		@message1 = json["message1"].encode(@message1.encoding) if json["message1"]
		@message2 = json["message2"].encode(@message2.encoding) if json["message2"]
		@message3 = json["message3"].encode(@message3.encoding) if json["message3"]
		@message4 = json["message4"].encode(@message4.encoding) if json["message4"]
	end

	def to_s
		s = "State: #{padVariable(@id, 3)}\n"
		s << super
		s << "Action Restrictions: #{parseRestriction(@restriction)}\n"
		s << "Display Priority: #{@priority}\n"
		s << "Remove at Battle End\n" if @remove_at_battle_end
		s << "Clear Action Restrictions\n" if @remove_by_restriction
		s << "Automatic Timed Release: #{parseAutoRelease(@auto_removal_timing)}\n"
		s << "Number of Turns Taken: #{@min_turns} ~ #{@max_turns}\n" unless @auto_removal_timing == 0
		s << "Remove by Damage: #{@chance_by_damage}%\n" if @remove_by_damage
		s << "Remove by Walking: #{@steps_to_remove} Steps\n" if @remove_by_walking
		s << "Inflicted Ally Message: #{@message1}\n" unless @message1.empty?
		s << "Inflicted Enemy Message: #{@message2}\n" unless @message2.empty?
		s << "Continued Infliction Message: #{@message3}\n" unless @message3.empty?
		s << "Recovery Message: #{@message4}\n" unless @message4.empty?
		return s
	end

	def getDiff(obj)
		diffs = super
		diffs << "Restriction changed" if @restriction != obj.restriction
		diffs << "Priority changed" if @priority != obj.priority
		diffs << "Remove at Battle end changed" if @remove_at_battle_end != obj.remove_at_battle_end
		diffs << "Remove by Restriction changed" if @remove_by_restriction != obj.remove_by_restriction
		diffs << "Auto Removal Timing changed" if @auto_removal_timing != obj.auto_removal_timing
		diffs << "Min Turns changed" if @min_turns != obj.min_turns
		diffs << "Max Turns changed" if @max_turns != obj.max_turns
		diffs << "Remove by Damage changed" if @remove_by_damage != obj.remove_by_damage
		diffs << "Chance by Damage changed" if @chance_by_damage != obj.chance_by_damage
		diffs << "Remove by Walking changed" if @remove_by_walking != obj.remove_by_walking
		diffs << "Steps to Remove changed" if @steps_to_remove != obj.steps_to_remove
		diffs << "Message 1 changed" if @message1 != obj.message1
		diffs << "Message 2 changed" if @message2 != obj.message2
		diffs << "Message 3 changed" if @message3 != obj.message3
		diffs << "Message 4 changed" if @message4 != obj.message4
		return diffs
	end

	# The attribute positions of the json file generated by this will not match those of RPG Maker MV
	# because there are several strange changes in the positions of attributes and I did not manage
	# to figure out the complete pattern.
	def to_json(*a)
		json = {
			"id" => @id,
			"autoRemovalTiming" => @auto_removal_timing,
			"chanceByDamage" => @chance_by_damage
		}
		json.merge!({"description" => @description}) if @description != nil
		json.merge!({
			"iconIndex" => @icon_index,
			"maxTurns" => @max_turns,
			"message1" => @message1,
			"message2" => @message2,
			"message3" => @message3,
			"message4" => @message4,
			"minTurns" => @min_turns,
			"motion" => @motion,
			"overlay" => @overlay,
			"name" => @name,
			"note" => @note,
			"priority" => @priority
		})
		json.merge!({"releaseByDamage" => @releaseByDamage}) if @releaseByDamage != nil
		json.merge!({
			"removeAtBattleEnd" => @remove_at_battle_end,
			"removeByDamage" => @remove_by_damage,
			"removeByRestriction" => @remove_by_restriction,
			"removeByWalking" => @remove_by_walking,
			"restriction" => @restriction,
			"stepsToRemove" => @steps_to_remove,
			"traits" => @features})
		
		return json.to_json(*a)
	end

	attr_accessor :restriction
	attr_accessor :priority
	attr_accessor :remove_at_battle_end
	attr_accessor :remove_by_restriction
	attr_accessor :auto_removal_timing
	attr_accessor :min_turns
	attr_accessor :max_turns
	attr_accessor :remove_by_damage
	attr_accessor :chance_by_damage
	attr_accessor :remove_by_walking
	attr_accessor :steps_to_remove
	attr_accessor :message1
	attr_accessor :message2
	attr_accessor :message3
	attr_accessor :message4
end